const buttons = [
    {	
        butregion:'华北',
        city:[
            {name:'北京'},
            {name:'天津'},
            {name:'河北'},
            {name:'山西'},
            {name:'内蒙古'}
        ]
    },
    {
        butregion:'东北',
        city:[
            {name:'辽宁'},
            {name:'吉林'},
            {name:'黑龙江'},
        ]
    },
    {
        butregion:'华东',
        city:[
            {name:'上海'},
            {name:'江苏'},
            {name:'浙江'},
            {name:'江西'},
            {name:'安微'},
            {name:'福建'},
            {name:'山东'}
        ]
    },
    {
        butregion:'中南',
        city:[
            {name:'河南'},
            {name:'湖北'},
            {name:'湖南'},
            {name:'广东'},
            {name:'广西'},
            {name:'海南'}
        ]
    },
    {
        butregion:'西南',
        city:[
            {name:'重庆'},
            {name:'四川'},
            {name:'贵州'},
            {name:'云南'},
            {name:'西藏'}
        ]
    },
    {
        butregion:'西北',
        city:[
            {name:'陕西'},
            {name:'甘肃'},
            {name:'青海'},
            {name:'宁夏'},
            {name:'新疆'}
        ]
    },
    {
        butregion:'港澳台',
        city:[
            {name:'香港'},
            {name:'澳门'},
            {name:'台湾'},
        ]
    },
];

export default buttons;